### PR TITLE
add tools image of gh.com/container-images

### PR DESCRIPTION
**Pull request by TomasTomecek**
Let me know if I can provide any help.

### CODE REVIEW

**Comment by mohammedzee1000** [comment]
@TomasTomecek https://github.com/CentOS/container-pipeline-service this is the service repo. Any helpful contributions would be welcome :)

**Comment by TomasTomecek** [comment]
I have no idea how to set it up: https://github.com/CentOS/container-pipeline-service/issues/345

**Comment by mohammedzee1000** [comment]
@TomasTomecek the app id and the filename in filename.yml should match

**Comment by TomasTomecek** [comment]
Right, thanks for info.

I just updated it.

**Comment by kbsingh** [comment]
In order to unblock this issue, I would recommend doing the template renders in a ci.centos.org job, and have that in turn trigger the builds ( either as its own git repo, that only gets content via the ci job, or elsewhere ). That would allow @TomasTomecek  to keep running his repo as is, and the container pipeline to build, and run as it does today.

**Comment by TomasTomecek** [comment]
please let me know if we can help in any way

**Comment by bamachrn** [comment]
ok to test

**Comment by bamachrn** [comment]
@mohammedzee1000 you want to check hy this is failing?

**Comment by mohammedzee1000** [comment]
@bamachrn ah the ci code needs to be updated. Obviously target file wont be present if pre-build is specified.

**Comment by mohammedzee1000** [comment]
Fixing the index ci https://github.com/CentOS/container-pipeline-service/pull/378 F

**Comment by bamachrn** [comment]
ok to test

**Comment by bamachrn** [comment]
ok to test

**Pull request merged**
