### PR TITLE
bump gogs to 0.11.19

### PR DESCRIPTION
**Pull request by kbsingh**

### CODE REVIEW

**Comment by kbsingh** [comment]
@mohammedzee1000 what is the problem here ? my bit looks clean

**Comment by mohammedzee1000** [comment]
@dharmit  ^ we have a branch going missing again on eclipse. Che stack centos_python branch referenced at  https://github.com/CentOS/container-index/blob/master/index.d/che-stacks.yml#L72 has gone missing

@kbsingh ^

**Comment by mohammedzee1000** [comment]
@kbsingh once ci passes, you can merge this and go ahead.

**Comment by bamachrn** [comment]
ok to test

**Pull request merged**
