### PR TITLE
Added entries for openshift based jenkins containers.

### PR DESCRIPTION
**Pull request by mohammedzee1000**

### CODE REVIEW

**Comment by mohammedzee1000** [comment]
Required merge of https://github.com/CentOS/container-index/pull/76 to clear.

**Comment by mohammedzee1000** [comment]
ok to test

**Comment by mohammedzee1000** [comment]
Still waiting on #76

**Comment by mohammedzee1000** [comment]
ok to test

**Comment by mohammedzee1000** [comment]
ok to test

**Comment by mohammedzee1000** [comment]
I have rebased this PR, once CI passes, we should be good to merge and get openshift based jenkins containers

**Comment by mohammedzee1000** [comment]
ok to test

**Comment by mohammedzee1000** [comment]
ok to test

**Comment by mohammedzee1000** [comment]
ok to test

**Comment by mohammedzee1000** [comment]
ok to test

**Comment by mohammedzee1000** [comment]
ok to test

**Comment by bamachrn** [comment]
ok to test

**Pull request merged**
