### PR TITLE
Fix .NET builder image dependency.

### PR DESCRIPTION
**Pull request by jerboaa**
Use correct image:

dotnet/dotnet-20-runtime-centos7

vs.

centos/dotnet-20-runtime-centos7

### CODE REVIEW

**Comment by tmds** [comment]
Is this the appropriate place? There seems to be a lot of s2i stuff in sclo.yml?

**Comment by jerboaa** [comment]
I don't think sclo.yml is the right place either. It's a different group maintaining them. Almost all images are builder images these days.

**Comment by jerboaa** [comment]
@bamachrn Could we get this merged, please?

**Comment by jerboaa** [comment]
Thanks!

**Pull request merged**
