### PR TITLE
Update ccp-openshift containers

### PR DESCRIPTION
**Pull request by navidshaikh**
- Updates the git-url and git-path for ccp-openshift-scan container
 - Updates the git-url and git-path for ccp-openshift-slave container

### CODE REVIEW

**Comment by dharmit** [comment]
ok to test

**Comment by mohammedzee1000** [comment]
We might need to rerun as a fix for desired tag was not in when this was triggered

**Comment by mohammedzee1000** [comment]
ok to test

**Comment by navidshaikh** [comment]
ok to test

**Comment by navidshaikh** [comment]
ok to test

**Comment by bamachrn** [comment]
ok to test

**Comment by mohammedzee1000** [comment]
Merging

**Pull request merged**
