### PR TITLE
Bumped up the origin container version to v1.3.1 and latest.

### PR DESCRIPTION
**Pull request by mohammedzee1000**
This is keeping with the discussion with @tdawson about
delivering the latest release of openshift containers.

### CODE REVIEW

**Comment by kbsingh** [comment]
what is going to happen to the 1.2.1 containes ?

**Comment by mohammedzee1000** [comment]
We will need to work with openshift guys to update the release-1.2 branch dockerfiles to install specific version of openshift, instead of relying on yum to pick up the latest.

@tdawson comments?

**Comment by tdawson** [comment]
I thought in that discussion we said we were following the roadmap of upstream origin.  That we only support the latest version, in this case 1.3.
If we are going to be supporting the software different than upstream, then we need to fork the branch and support it in our own repo, not continuing to push our stuff upstream.

**Comment by mohammedzee1000** [comment]
Alright unless someone has a better solution, I say we go ahead and provide latest release and latest and greatest from upstream and older versions from @tdawson s fork. Basically, whenever there is a release , we bump up version for upstream repo and create fork/branch for older version. We should limit the older versions we provide though @kbsingh, @bamachrn, @rtnpro thoughts?

**Comment by bamachrn** [comment]
@tdawson in this case if there is any update/security update required for the base container of older version, lets say v1.2.1 then do we just ignore them or we update them with origin rpm v1.2.1?
If we are planning to ignore them then it sounds good. But if we are planning to keep the older version images updated then we need to get a way to fix rpm versions. what you say? @tdawson @kbsingh @mohammedzee1000

**Comment by kbsingh** [comment]
@tdawson @mohammedzee1000 @bamachrn - i think the scope of the effort is much smaller in nature : we should ship the 1.2.1 containers, while there are rpms for it in the corrosponding yum-repos. It might never get an update, much like the 1.2.1 rpms, but it allows folks to deploy what they need, and make the knowledgeable switch when needed.

I believe the problem we have now, wherein we had 1.3 content shipped into a 1.2 tag'd container was just down to issues in the way we execute the builds on our side. And we should investigate that, and fix it if possible. So in essence we should have right now : 
* 1.2.1 containers
* 1.3.0 containers
* latest tag's that map to 1.3.0 
and we just stop building anything to 1.2.1; when 1.4 is released or a 1.3.1, we then stop building 1.3.0 containers and just do the new ones, and move the latest tag to the new ones, leaving 1.2.1 and 1.3.0 containers as is.

Longer term we will need to workout a purge strategy, and it should ideally match an external criteria ( in this case, rpms trimmed from the pass sig openshift-origin repos ).

**Comment by mohammedzee1000** [comment]
That works, we should add a new flag to the index to indicate this. Maybe something like maintained: true (or false). If an entry has maintained set to false, then nothing should trigger the container rebuilds.

We should then ensure that we have a backup of the un-maintained containers so that they can be re-pushed, in case of loss of data in the registry.

**Comment by mohammedzee1000** [comment]
PR updated to keep the original 1.2.1 entries and add entries for  1.3.1 origin containers, which will also be tagged as latest.

**Comment by mohammedzee1000** [comment]
@tdawson, i heard there was a 1.3.1 release on origin, do we have rpms for the same yet?

**Comment by tdawson** [comment]
I do, but it's still in testing, I haven't had time to run through a
testing sweep of it.

**Comment by mohammedzee1000** [comment]
1.3.1 rpms are out i thing we should be good once #69 is in and i rebase to the same.

**Pull request merged**
