### PR TITLE
Add .NET Core 2.0 Jenkins slave image

### PR DESCRIPTION
**Pull request by tmds**
Depends on https://github.com/redhat-developer/dotnet-jenkins-slave/pull/5

CC @jerboaa

### CODE REVIEW

**Comment by jerboaa** [comment]
Not sure what's up with the CI job. Looks like a strange outside-our-control failure ;-)

**Comment by mohammedzee1000** [comment]
@jerboaa Found the issue and will fix in a minute. You will need to merge the linked PR though as the CI expects cccp.yml to be present in the git repository.

**Comment by tmds** [comment]
@mohammedzee1000 the referenced PR has been merged.

**Comment by mohammedzee1000** [comment]
@tmds ok, then we just need my fix to go in and we should be good. I didnt expect the git path to just be a number frankly

https://github.com/CentOS/container-pipeline-service/pull/357

**Comment by tmds** [comment]
@mohammedzee1000 I can add a backslash if you like (like https://github.com/CentOS/container-index/blob/master/index.d/sclo.yml)

**Comment by mohammedzee1000** [comment]
@tmds that should work too. It should get your PR in.

**Pull request merged**
