### PR TITLE
Add .NET Core 2.0 images.

### PR DESCRIPTION
**Pull request by jerboaa**
These are CentOS mirror images of
registry.access.redhat.com/dotnet/dotnet-20{,-runtime}-rhel7

### CODE REVIEW

**Comment by mohammedzee1000** [comment]
@jerboaa The appids inside the file must match the filename, so in your case, either change filename to dotnetcore.yml or change app id to dotnet. This is currently a requirement of the pipeline.

**Comment by jerboaa** [comment]
@mohammedzee1000 Thanks. Hopefully this works now :)

**Comment by mohammedzee1000** [comment]
@jerboaa no problem. It should work. The CI you see here does validation of the yml format and values only, the actual execution of build is done by pipeline once PR is merged.

**Comment by jerboaa** [comment]
OK. Got it.

**Comment by jerboaa** [comment]
@mohammedzee1000 How would we trigger a new build? `cccp.yml` files should be there now.

**Comment by bamachrn** [comment]
ok to test

**Comment by mohammedzee1000** [comment]
@jerboaa ok its no longer issue with your entries. Give me a few minutes. You will need to rebase once i tell you.

**Comment by mohammedzee1000** [comment]
https://github.com/CentOS/container-index/pull/214 this should fix the error. @jerboaa once its merged, you can rebase and we should be good.

**Comment by bamachrn** [comment]
ok to test

**Comment by jerboaa** [comment]
Thank you!

**Pull request merged**
