### PR TITLE
Changed desired-tag to 1.2.1 on origin and added it to bamachrn.

### PR DESCRIPTION
**Pull request by mohammedzee1000**
This is for purpose of properly building origin 1.2.1 containers
and in prepration for origin 1.3.

### CODE REVIEW

**Comment by navidshaikh** [comment]
Should we have an issue associated with PR explaining the problem being fixed ?

**Comment by mohammedzee1000** [comment]
The problem is getting usable origin containers out the other side. WIth 1.3 being released and rpm enroute, we should tag this openshift with version ie :1.2.1, so that the newer images 1.3 images can be tagged latest.

**Comment by navidshaikh** [comment]
> so that the newer images 1.3 images can be tagged latest.

Alright!

Build is failing though! 
I think we need to add `desired-tag` field for 3 entries in https://github.com/CentOS/container-index/blob/master/index.d/bamachrn.yml#L14-L42 , they are missing ATM.

**Comment by mohammedzee1000** [comment]
@navidshaikh yes, they are but we will have to ignore that for now @bamachrn will fix that once this pr is merged. I had added that to the PR but removed it from here.

**Comment by navidshaikh** [comment]
> they are but we will have to ignore that for now
Why? 

@bamachrn ?

**Comment by bamachrn** [comment]
We have kept desired-tag as latest by default, I intentionally did not add desired-tag there. I am adding and raising PR against that

**Comment by navidshaikh** [comment]
> We have kept desired-tag as latest by default, I intentionally did not add desired-tag there. I am adding and raising PR against that

Why to create two separate PRs? If there is nothing going to break by not creating two separate PRs, let @mohammedzee1000 update this PR itself.

**Comment by bamachrn** [comment]
@navidshaikh they are referring to two different projects its better to keep them in separate PR

**Comment by navidshaikh** [comment]
>@navidshaikh they are referring to two different projects its better to keep them in separate PR

I see it as container-index project and the common fix between multiple input artifacts. 
IMO, it is not separation of concern, if we have to merge the PRs having non green CI.

**Comment by navidshaikh** [comment]
To be merged with https://github.com/CentOS/container-index/pull/44/

**Comment by navidshaikh** [comment]
LGTM ( Beside the CI has failed and reason is discussed above)

**Pull request merged**
