### PR TITLE
Moving from index.yml to index.d

### PR DESCRIPTION
**Pull request by mohammedzee1000**
This is based on the decision to move from single index.yml to one yml per namespace inside an index.d directory.

The changes done include moving the index.yml content into the new index.d files alongwith update to the readme.

### CODE REVIEW

**Comment by bamachrn** [comment]
we can merge container-pipeline and pipeline-images together as pipeline-images?

**Comment by mohammedzee1000** [comment]
@bamachrn done check the pipeline-images.yml file. Also @bamachrn @kbsingh please review this while i work on service change

**Comment by mohammedzee1000** [comment]
Validated on allinone

**Comment by bamachrn** [comment]
LGTM

**Pull request merged**
