### PR TITLE
Added pgweb container to the container index.

### PR DESCRIPTION
**Pull request by mohammedzee1000**
Currently build from my fork
Upstream PR :  https://github.com/CentOS/CentOS-Dockerfiles/pull/108

### CODE REVIEW

**Comment by navidshaikh** [comment]
Contents looks okay to me, are we going to index the build with reference to git repo under your namespace? and once the upstream is merged, we are going to raise another PR to change the namespace ?

**Comment by mohammedzee1000** [comment]
I am not sure if i want to go back to users who currently need this container and ask them to update their container names twice in their deployments.

**Comment by navidshaikh** [comment]
> I am not sure if i want to go back to users who currently need this container and ask them to update their container names twice in their deployments.

I am saying about the source repository, the name of container and name of repository are two different entities, and can be modified without depending on other.

**Comment by mohammedzee1000** [comment]
@navidshaikh yes, the repo can be updated with the maximum affect of container rebuild (which should not affect container availability) so long as name of the container does not change.

**Comment by navidshaikh** [comment]
> @navidshaikh yes, the repo can be updated with at the most affect of container rebuild (which should not affect container availability) so long as name of the container does not change.

Alright, thats the plan then.

Let's work through the other PR's closure.

**Pull request merged**
