### PR TITLE
build a second container with no tag

### PR DESCRIPTION
**Pull request by kbsingh**
i need to be able to pull this image without using the :latest tag from openshift.

### CODE REVIEW

**Comment by kbsingh** [comment]
ok to test

**Comment by kbsingh** [comment]
unsure as to what the best way to move forward on this is - are we unable to do builds without a desired-tag at this point ?

**Comment by navidshaikh** [comment]
> are we unable to do builds without a desired-tag at this point ?

We should be able to build without desired-tag, check https://github.com/CentOS/container-pipeline-service/blob/master/jenkinsbuilder/cccp_index_reader.py#L65-L68 , incase of missing `desired-tag` field, it uses `latest` tag, 
however CI tests are going to fail since we coded it as mandatory field check https://github.com/CentOS/container-pipeline-service/blob/master/testindex/Validators.py#L100

**Comment by kbsingh** [comment]
@navidshaikh : since it adds the tag on its own, that means even if we are able to get it through the index. the resulting image will still be unusable in openshift. We might need to look at this, since a large number of our use-cases are openshift centric.

**Comment by kbsingh** [comment]
closing the issue for now, we will need to workout a diferent plan to map through this, since the latest bit is the default anyway

**Pull request closed without merging**
