### PR TITLE
Adding 'centos-quarkus.io-jdk8' stack to container-index

### PR DESCRIPTION
**Pull request by ibuziuk**
Related che PR https://github.com/eclipse/che-dockerfiles/pull/240
Related rh-che PR - https://github.com/redhat-developer/che-dockerfiles/pull/54

### CODE REVIEW

**Comment by ibuziuk** [comment]
cc: @vorburger

**Comment by ibuziuk** [comment]
@bamachrn @dharmit could you please merge?

**Comment by dharmit** [comment]
ok to test

**Comment by ibuziuk** [comment]
@dharmit build looks broken for a while - https://ci.centos.org/job/centos-container-index-ci/ 
is it a blocker for merging?

**Comment by dharmit** [comment]
> @dharmit build looks broken for a while - https://ci.centos.org/job/centos-container-index-ci/
> is it a blocker for merging?

@ibuziuk Yes, you are right. I took a look to see if something related to quarkus was off but it doesn't look that way. I'm inclined to merge this but am a bit hesitant to do it immediately due to a `.` in the name. I'm giving this a spin in my environment to be sure.

If all goes well, I'll merge it in the morning. It's nearly midnight here. :wink:

**Comment by ibuziuk** [comment]
@dharmit FYI having a dot is correct in quay repos [1]
https://gitlab.cee.redhat.com/service/app-interface/merge_requests/397/diffs

**Comment by dharmit** [comment]
LGTM. Merging since the CI errors don't seem to be related to the PR in question.

**Comment by ibuziuk** [comment]
@dharmit looks like there still 

```Step 1/18 : FROM registry.centos.org/che-stacks/centos-quarkus.io-jdk8
Trying to pull repository registry.centos.org/che-stacks/centos-quarkus.io-jdk8 ... 
Pulling repository registry.centos.org/che-stacks/centos-quarkus.io-jdk8
Error: image che-stacks/centos-quarkus.io-jdk8:latest not found
```
how should the initial image `registry.centos.org/che-stacks/centos-quarkus.io-jdk8` happen with the current flow?

**Comment by bamachrn** [comment]
@dharmit  @ibuziuk  image is pushed as `registry.centos.org/che-stacks/centos-quarkus-io-jdk8:latest` we are looking for `quarkus.io`?

**Comment by vorburger** [comment]
So `docker pull registry.centos.org/che-stacks/centos-quarkus-io-jdk8:latest` seems to work now (as in it pulls, haven't actually tested the image, yet). I can't find it on the UI though, and have opened https://github.com/CentOS/container-pipeline-service/issues/689 about that.

**Pull request merged**
