### PR TITLE
Add softwareafactory-project to the index

### PR DESCRIPTION
**Pull request by javierpena**
Initially, we will only be building a container for the DLRN API [1].

[1] - https://github.com/softwarefactory-project/DLRN

### CODE REVIEW

**Comment by navidshaikh** [comment]
ok to test

**Comment by javierpena** [comment]
I see the failed checks are related to other files. Is this something that should be fixed as part of this PR, or elsewhere?

**Comment by bamachrn** [comment]
> I see the failed checks are related to other files. Is this something that should be fixed as part of this PR, or elsewhere?

Hi @javierpena we are looking into this, will get back.

**Comment by bamachrn** [comment]
merging this as CI passed for this entry, while we fix the entries with errors

**Comment by bamachrn** [comment]
Hi @javierpena the build pipeline is facing one issue in the pod allocation. we are working on that. you will receive email on image getting built.

**Comment by javierpena** [comment]
Thanks for the heads up @bamachrn, I'll wait for the email.

**Comment by bamachrn** [comment]
your image is published in the registry. I believe you  have received an email as well. We are taking the system in maintenance mode. once the system is back you will be able to check the logs and all through https://registry.centos.org/softwarefactory-project/dlrnapi

**Comment by javierpena** [comment]
I got the e-mail, and just tested that pulling the image from the registry works. Thanks!

**Pull request merged**
