### PR TITLE
Add entries for CentOS Dockerfiles

### PR DESCRIPTION
**Pull request by dharmit**
This PR adds entries for those projects in [CentOS-Dockerfiles](https://github.com/CentOS/CentOS-Dockerfiles) repo that are not already present in the index.

### CODE REVIEW

**Comment by dharmit** [comment]
ping @mohammedzee1000 @bamachrn

**Comment by bamachrn** [comment]
LGTM, lets wait for CI

**Comment by mohammedzee1000** [comment]
CI will likely not go green as index is broken. Fix up in https://github.com/CentOS/container-index/pull/384
Merge after this goes in

**Comment by dharmit** [comment]
#dotests

**Pull request merged**
