### PR TITLE
Added entries for origin containers.

### PR DESCRIPTION
**Pull request by mohammedzee1000**
This is for the purpose of building openshift origin containers through pipeline

### CODE REVIEW

**Comment by mohammedzee1000** [comment]
Wait for upstream PR to be merged

https://github.com/openshift/origin/pull/9864

**Comment by mohammedzee1000** [comment]
Upstream PR has been merged. I have even validated the entries through the testindex script.
We should be good to merge this.

**Comment by kbsingh** [comment]
Hi,

Just to recap the conversation so we've had so far around this : the dockerfiles merged upstream that we can track all point at the origin 1.3 release, whereas the builds we have via the PaaS  SIG are for 1.2.x - how are we going to handle this ?

cc: @tdawson

**Comment by mohammedzee1000** [comment]
@kbsingh we could pull the images, tag them with a 1.2.x tag and push them back out. We can then update the latest to be the new containers.

@bamachrn @dharmit any inputs?

**Comment by bamachrn** [comment]
I would also not vote for manual tagging, we need to come up with custom tagging from pipeline.

**Comment by mohammedzee1000** [comment]
Maybe we can get the 1.2 version rpm based dockerfiles into https://github.com/openshift/origin/tree/release-1.2. This way we can track 1.2 and 1.3 in the openshift-origin repositories.

**Comment by tdawson** [comment]
@mohammedzee1000 I think we should be able to do that, now that we have something in master (1.3).  We should be able to do something similar in the 1.2 branch.

**Comment by mohammedzee1000** [comment]
@tdawson cool, so maybe i can work with you and get this done?

**Comment by tdawson** [comment]
I have the pull request done
https://github.com/openshift/origin/pull/10224
I need someone, other than me, to test it.

**Comment by mohammedzee1000** [comment]
The PR has been merged i will work on updating this once we have desired tag functionality and i have verified that these containers can be built.

**Comment by mohammedzee1000** [comment]
@tdawson i tried building the containers manually and they build fine when i tag them as latest. However, when version is used (eg : openshift/origin:1.2), it fails at openshift/origin, when built in order. Any idea why this is so?

**Comment by mohammedzee1000** [comment]
@tdawson i tried building the containers manually and they build fine when i tag them as latest. However, when version as tag is used (eg : openshift/origin:1.2), it fails at openshift/origin, when built in order. Any idea why this is so?

The docker build fails while installing the rpms

Note i am rerunning to verify this and will update.

**Comment by mohammedzee1000** [comment]
Verified check http://pastebin.centos.org/52201/ for docker build log.

**Comment by mohammedzee1000** [comment]
I tried being very specific with the tag openshift/origin:1.2.1 (did this for all the images and rebuilt in same order, from scratch)

http://pastebin.centos.org/52231/

**Comment by mohammedzee1000** [comment]
ok, i guess its working now, updating PR with release-1.2 entries

**Comment by mohammedzee1000** [comment]
Updated the origin containers to the new index.d format. ping @bamachrn @kbsingh

**Comment by kbsingh** [comment]
lgtm, lets get 1.2.1 done

**Pull request merged**
