### PR TITLE
Remove eclipse-che-dev image from container-index

### PR DESCRIPTION
**Pull request by dharmit**
This image is way outdated and keeps failing in the service. We don't have any users for it. ping @bamachrn

### CODE REVIEW

**Comment by bamachrn** [comment]
@dharmit there is any updated version for this? I mean is there something replacing this in OSIO?

**Comment by dharmit** [comment]
This was put into index long back. The Che devs use images from `che-stacks.yml` file. 

I think @l0rd can give us 100% accurate answer if this is being moved to something else in OSIO.

**Comment by mohammedzee1000** [comment]
work wise it looks good to me. Do we want to wait on @l0rd before we go ahead and merge this?

**Comment by l0rd** [comment]
I don't know what this image was used for. Ok to delete for me. And che-starter one too I guess (the source is your fork @dharmit that is probably not updated anyway).

**Comment by dharmit** [comment]
@l0rd thanks!

@mohammedzee1000 @bamachrn this is good to merge. I'll open another PR for removing che-starter from the index. These entries were added long back when I was working to port things from Alpine to CentOS.

**Pull request merged**
