### PR TITLE
Add .NET 5.0 images.

### PR DESCRIPTION
**Pull request by aslicerh**

### CODE REVIEW

**Comment by aslicerh** [comment]
Ping? Can someone take a look at this?

**Comment by kbsingh** [comment]
this looks fine, @bamachrn any concerns ?

**Review by bamachrn — APPROVED** [review]

**Comment by bamachrn** [comment]
@aslicerh  images are now available in registry. notifications are failing that's why build status are shown as failure. We are working on that.

**Comment by aslicerh** [comment]
@kbsingh Thanks for taking a look!

@bamachrn Noted, and thanks for the update!

**Pull request merged**
