### PR TITLE
Add entry to build che-server using pipeline

### PR DESCRIPTION
**Pull request by dharmit**
ping @bamachrn @kbsingh

### CODE REVIEW

**Comment by bamachrn** [comment]
@dharmit Please add git-path as / (i.e. git-path: / )

**Comment by dharmit** [comment]
@bamachrn thanks, fixed, build passed. :smile:

**Comment by kbsingh** [comment]
Lgtm

**Comment by l0rd** [comment]
@kbsingh @dharmit I can't `docker pull registry.centos.org/eclipse/che-server:latest` yet. Is there a way to know if the image has been built successfully?

**Pull request merged**
