### PR TITLE
Add mattermost, mattermost-gitlab-integration

### PR DESCRIPTION
**Pull request by syamgk**

### CODE REVIEW

**Comment by bamachrn** [comment]
#dotests

**Comment by mohammedzee1000** [comment]
ok to test

**Comment by dharmit** [comment]
ok to test

**Comment by dharmit** [comment]
ok to test

**Comment by mohammedzee1000** [comment]
@sgk you seem to have a missing cccp.yml file in https://github.com/syamgk/mattermost-gitlab-integration
Please add it to the repository in the gitpath

**Comment by syamgk** [comment]
@mohammedzee1000 updated the repo with cccp.yml

**Comment by mohammedzee1000** [comment]
ok to test

**Comment by bamachrn** [comment]
LGTM

**Pull request merged**
