### PR TITLE
projectatomic: Add the CRI-O and Docker system containers

### PR DESCRIPTION
**Pull request by giuseppe**
They are maintained here:

https://github.com/projectatomic/atomic-system-containers/tree/master/cri-o-centos

and

https://github.com/projectatomic/atomic-system-containers/tree/master/docker-centos

### CODE REVIEW

**Comment by mohammedzee1000** [comment]
@giuseppe can we have the git paths start with /cri-o-centos, for example. It gives clarity as in the git path is w.r.t repository root.

**Comment by mohammedzee1000** [comment]
Also, you need to add a cccp.yml file to the repositories in the git path. Template for same is available in index (https://github.com/CentOS/container-index/blob/master/cccp.yml). Only job-id is compulsory.

**Comment by giuseppe** [comment]
@mohammedzee1000 thanks for the quick review, I've opened a PR here for adding the missing files:

https://github.com/projectatomic/atomic-system-containers/pull/140

We use Homu to merge the PRs on projectatomic.  I added you as an approver, if the other PR looks good to you, please merge it using "@rh-atomic-bot r+ bb18074"

**Comment by mohammedzee1000** [comment]
#dotests

**Comment by mohammedzee1000** [comment]
ok to test

**Comment by giuseppe** [comment]
thanks!  Is there a way to force immediately a rebuild if something changed in the image?  Otherwise, how long does it usually take before new changes are propagated from github?

**Comment by mohammedzee1000** [comment]
@giuseppe The git repositories are polled regularly atm. So they should be picked up on the next poll, and unless there is a big stack of builds, you should receive the build report pretty quickly. 

As far as manual builds are concerned, if you really need something quick, you can me or @bamachrn and we should be able to trigger a manual build for you.

**Pull request merged**
