### PR TITLE
Deprecate PHP-7.2 and NGINX-1.14

### PR DESCRIPTION
**Pull request by phracek**
Images are EOL since Nov 2020

Signed-off-by: Petr "Stone" Hracek <phracek@redhat.com>

### CODE REVIEW

**Comment by phracek** [comment]
[test]

**Comment by phracek** [comment]
Can it be merged?

**Comment by bamachrn** [comment]
@phracek even though we merge it, we do not remove the container images from the registry. Do we really want to remove the image layers from the registry or just removing it from UI?

**Comment by phracek** [comment]
Just remove it from UI. The container images are not built at all.

CC @pkubatrh @hhorak

**Pull request merged**
