### PR TITLE
Updated jboss dockerfiles to use upstream repos for build.

### PR DESCRIPTION
**Pull request by mohammedzee1000**

### CODE REVIEW

**Comment by mohammedzee1000** [comment]
@kbsingh @bamachrn can we get this merged. This also fixes an entry that broke after index was updated.

**Comment by kbsingh** [comment]
Why are we using upstream base and not building it ourselves?

**Comment by mohammedzee1000** [comment]
@kbsingh the upstream base is maintained by the jboss community and its also based on centos:7. So i see little reason to fork it.

**Comment by mohammedzee1000** [comment]
@kbsingh @bamachrn can we get this merged

**Comment by bamachrn** [comment]
@mohammedzee1000 lets merge this post deployment

**Comment by mohammedzee1000** [comment]
@bamachrn ok

**Comment by mohammedzee1000** [comment]
@bamachrn @kbsingh i guess we can get this merged now

**Pull request merged**
