### PR TITLE
Adding openshift origin 3.9 containers to the container index.

### PR DESCRIPTION
**Pull request by mohammedzee1000**
This PR adds openshift origin 3.9 to the container index.

Signed-off-by: Mohammed Zeeshan Ahmed <mohammed.zee1000@gmail.com>

### CODE REVIEW

**Comment by mohammedzee1000** [comment]
cc @tdawson @stevekuznetsov

**Comment by mohammedzee1000** [comment]
We need a cccp.yml file for origin-source

**Comment by mohammedzee1000** [comment]
https://github.com/openshift/origin/pull/19859 @tdawson @sdodson @stevekuznetsov

**Comment by mohammedzee1000** [comment]
@bamachrn do you want to merge this, don't feel like doing this to my own pr

**Comment by bamachrn** [comment]
you checked them by building once right? merging

**Pull request merged**
