### PR TITLE
Adds projects to ci branch for pipeline service continuous integration

### PR DESCRIPTION
**Pull request by navidshaikh**
Added only 3 projects in container-index for CI run.
  The notify email now points to container-status-report@centos.org

### CODE REVIEW

**Comment by navidshaikh** [comment]
#dotests

**Comment by navidshaikh** [comment]
#dotests

**Comment by navidshaikh** [comment]
again merge with review! @bamachrn

**Comment by bamachrn** [comment]
did a review before merge, ok. I need to mention it in GH. got it

**Pull request merged**
